services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auctionDb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data